### ISSUE TITLE
Inconsistent Nonce API

### ISSUE THREAD

**Issue by jmjauer** [apple/swift-crypto#126]
The current AES.GCM.SealedBox API is inconsistent:

```swift
let message = "foo".data(using: .utf8)!
let key = SymmetricKey(size: .bits256)
let nonce = try AES.GCM.Nonce(data: Data(repeating: 0, count: 12))
let seal = try AES.GCM.seal(message, using: key, nonce: nonce)
let sealData = seal.combined
```

1. `sealData` is `Data?` and `nil` if `nonce.count != 12`.
2. `AES.GCM.Nonce(data: Data)` only allows `data` of `data.count == 12`, otherwise it will throw an error.

Since it is not possible to create a nonce with a size other than 12, `seal.combined` can never return `nil` and should not be `Data?` but `Data`.

**Comment by Lukasa** [comment]
> `AES.GCM.Nonce(data: Data)` only allows `data` of `data.count == 12`, otherwise it will throw an error.

This is not true, the code rejects larger nonces but allows smaller ones:

https://github.com/apple/swift-crypto/blob/4832fa0d133b9e03077040f123a9087e23ed21dd/Sources/Crypto/AEADs/Nonces.swift#L37-L43

**Comment by jmjauer** [comment]
Ah i see, my bad

**Comment by jmjauer** [comment]
My wrong assumption comes from Apples incorrect documentation:

https://developer.apple.com/documentation/cryptokit/aes/gcm/nonce/3237389-init

**Comment by FredericJacobs** [comment]
Good call, we'll get this fixed in a future SDK. Thanks!

**Comment by jmjauer** [comment]
> Good call, we'll get this fixed in a future SDK. Thanks!

The documentation has been changed, but I think it is still not correct. It says:

A 12-byte data representation of the nonce. The initializer throws an error if the data has a length other than 12 bytes.

Nonce larger than 12 bytes are valid, correct?
